---
- hosts: nginxsrv
  gather_facts: false
  roles:
    - { role: nginx_add_hosts, tags: ['nginx','hosts'] }
    - { role: nginx_install, tags: ['nginx','install'] }
    - { role: nginx_upload_conf, tags: ['nginx','conf'] }

- hosts: nginxsrv
  gather_facts: false
  roles:
    - { role: nginx_vrrp_install, tags: ['vrrp','vrrpinstall'] }
    - { role: nginx_vrrp_configure, tags: ['vrrp','vrrpconfigure'] }

- hosts: ubuntufarm
  gather_facts: false
  roles:
    - { role: add_record_to_hosts, tags: ['minio','hosts'] }
    - { role: firewall, tags: ['minio','firewall'] }
    - { role: minio_usr_grp, tags: ['minio','musrgrp'] }
    - { role: minio_setup, tags: ['minio','msetup']}
    - { role: mc_setup, tags: ['minio','mcsetup'] }
    - { role: minio_createdir, tags: ['minio','mcreate']}
    - { role: minio_run, tags: ['minio','mrun'] }

