---
- hosts: nginxsrv
  gather_facts: false
  roles:
    - { role: nginx_vrrp_install, tags: ['vrrp','nginxvrrpinstall'] }
    - { role: nginx_vrrp_configure, grpname: "{{ group_names }}", tags: ['vrrp','nginxvrrpconfigure'] }
