---
- name: Create minio group
  group:
    name: minio-user
    state: present

- name: Create minio user
  user:
    name: minio-user
    group: minio-user
    state: present
    comment: User for working with minio cluster
