---
- name: Upload conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx.conf

- name: Upload conf
  template:
    src: minio.site.j2
    dest: /etc/nginx/sites-available/minio{{ item.tenantid }}
  with_items:
    - { tenantid: 1, tenantport: 9001}
    - { tenantid: 2, tenantport: 9002}
  register: confout

- name: Create a symbolic link
  file:
    src: "{{ item.path }}"
    dest: "/etc/nginx/sites-enabled/{{ item.path | regex_replace('/etc/nginx/sites-available/', '') }}"
    state: link
  with_items: "{{ confout.results }}"

- name: Restart nginx
  service:
    name: nginx
    state: restarted
