---
- set_fact:
    init_value: 100

- name: Generate conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart_keepalived

- name: Add ability to get ip
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    state: present
    sysctl_set: yes
    reload: yes 
