---
- name: Upload minio binary to each nodes
  copy:
    src: minio
    dest: /usr/sbin/minio
    owner: minio-user
    group: minio-user
    mode: a+rwx

#- name: Create data dir for minio
#  file:
#    path: /mdata
#    state: directory

- name: Upload minio.service to each node
  copy:
    src: minio.service
    dest: /etc/systemd/system

- name: Upload minio default
  template:
    src: minio.default
    dest: /etc/default/minio
