---
- name: Upload minio binary to each nodes
  copy:
    src: minio
    dest: /usr/sbin/minio
    owner: minio-user
    group: minio-user
    mode: a+rwx

- name: Upload minio.service to each node
  copy:
    src: minio.service
    dest: /etc/systemd/system/minio@.service

- name: Upload minio default
  template:
    src: minio.default
    dest: "/etc/default/minio{{ item.tenantid }}"
    force: yes
  with_items:
    - { tenantid: 1, tenantport: "9001" }
    - { tenantid: 2, tenantport: "9002" }
