---
- name: Create dir for minio conf
  file:
    path: /root/.minio
    state: directory

- name: Force restart systemd
  systemd:
    daemon_reexec: yes

- name: Upload config json to each node
  copy:
    src: config.json
    dest: /root/.minio/config.json
    owner: minio-user
    group: minio-user

- name: Restart minio service
  service:
    name: minio
    state: restarted
  with_items:
    - minio@1
    - minio@2
