---
- name: Update apt
  shell: |
    rm -rf /etc/apt/sources.list.d/*nginx*
    echo "deb http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" >> /etc/apt/sources.list.d/nginx.list
    curl -fsSL https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
    apt-get clean
    apt-get update --allow-unauthenticated
    sudo apt-get -o DPkg::options::=--force-confmiss --reinstall install nginx
